config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :journals
  root 'journals#index'

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many :wins, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :metrics, dependent: :destroy

  accepts_nested_attributes_for :wins, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :lessons, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :metrics, reject_if: :all_blank, allow_destroy: true

  belongs_to :user

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :journal
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  belongs_to :journal
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :journals, dependent: :destroy
end

app/models/win.rb
class Win < ActiveRecord::Base
  belongs_to :journal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :find_journal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:year].present? && params[:month].present? && params[:day].present?
      @year = params[:year].to_s
      @month = params[:month].to_s
      @day = params[:day].to_s
      @date_string = @year + "" + @month + @day
      @journals = Journal.where(date: @date_string).order("date DESC")
    elsif params[:year].present? && params[:month].present?
      @year = params[:year].to_s
      @month = params[:month].to_s
      @date_string = "" + @year + @month
      @journals = Journal.where("to_char(date, 'YYYYMM')  = ?", @date_string).order("date DESC")

      @date = Date.parse(@date_string.concat("01"))
      @month_string = @date.strftime("%B")
      @display_dates = @date.week_split

    elsif params[:year].present?
      @year = params[:year].to_s
      @journals = Journal.where('extract(year from date) = ?', @date_string).order("date DESC")
    else
      @journals = Journal.all.order("date DESC")
    end
  end

  def show
    @year = @journal.date.year
    @month = @journal.date.strftime("%B")
    @day = @journal.date.mday
  end

  def new
    @journal = current_user.journals.build
  end

  def create
    @journal = current_user.journals.build(journal_params)

    if @journal.save
      redirect_to @journal, notice: "Successfully saved your daily journal!"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @journal.update(journal_params)
      redirect_to @journal
    else
      render 'edit'
    end
  end

  def destroy
    @journal.destroy
    redirect_to root_path, notice: "Successfully deleted your daily journal!"
  end

  private
  def journal_params
    params.require(:journal).permit(:date, :content, :improvement, :happiness, :meditation, :task_complete, :masturbation, :q1answers, :q2answers, :q3answers, :q4answers, wins_attributes: [:id, :win, :_destroy], lessons_attributes: [:id, :lesson, :_destroy])
  end

  def find_journal
    @journal = Journal.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
  def journal_graph_data
    Journal.group_by_day(:date).sum(:happiness)
  end

end

app/views/journals/_form.html.haml
= simple_form_for @journal, html: {multipart: true} do |f|
  - if @journal.errors.any?
    #errors
      %p
        = @journal.errors.count
        Prevented this journal from saving
      %ul
        - @journal.errors.full_messages.each do |msg|
          %li=msg

  .content
    .content_top
      = f.input :date, input_html: {class: "form-control date_input"}
      = f.input :improvement, input_html: {class: "form-control improvement_input"}
      .form-group.journal_metrics
        %label.text.control-label
          Daily Metrics
        .row.clearfix
          .journal_metrics_happiness
            = f.input :happiness, input_html: {class: "form-control"}
        .row.clearfix
          .journal_metrics_meditation
            = f.input :meditation, input_html: {class: "form-control"}
        .row.clearfix
          .journal_metrics_task_complete
            = f.input :task_complete, input_html: {class: "form-control"}
        .row.clearfix
          .journal_metrics_masturbation
            = f.input :masturbation, input_html: {class: "form-control"}

    .content_mid.clearfix
      .left.journal_questions
        = f.input :q1answers, label: "What's my wanted outcome?", input_html: {class: "form-control qa_input"}
        = f.input :q2answers, label: "Did I give it my all today?", input_html: {class: "form-control qa_input"}
        = f.input :q3answers, label: "Was today meaningful?", input_html: {class: "form-control qa_input"}
        = f.input :q4answers, label: "Was I doing what I love?", input_html: {class: "form-control qa_input"}
      .right
        .form-group.journal_win
          %label.text.control-label
            Wins of the Day
          = f.simple_fields_for :wins do |win|
            = render 'win_fields', f: win
          .links
            = link_to_add_association 'Add', f, :wins, class: "btn"

        .form-group.journal_lesson.clearfix
          %label.text.control-label
            Lessons of the Day
          = f.simple_fields_for :lessons do |lesson|
            = render 'lesson_fields', f: lesson
          .links
            = link_to_add_association 'Add', f, :lessons, class: "btn"

    .content_bot
      = f.input :content, label: "Daily Journal", input_html: {class: "form-control content_input"}
  = f.button :submit

app/views/journals/_lesson_fields.html.haml
.nested-fields
  .form-inline.clearfix
    = f.input :lesson, input_html: {class: "form-control"}
  = link_to_remove_association "Remove", f, class: "btn remove_btn"

app/views/journals/_metric_fields.html.haml
.nested-fields
  .row.clearfix
    = f.input :happiness, input_html: {class: "form-control"}
  .row.clearfix
    = f.input :meditation, input_html: {class: "form-control"}
  .row.clearfix
    = f.input :task_complete, input_html: {class: "form-control"}
  .row.clearfix
    = f.input :masturbation, input_html: {class: "form-control"}

  = link_to_remove_association "Remove", f, class: "btn remove_btn"

app/views/journals/_win_fields.html.haml
.nested-fields
  .form-inline.clearfix
    = f.input :win, input_html: {class: "form-control"}
  = link_to_remove_association "Remove", f, class: "btn remove_btn"

app/views/journals/edit.html.haml
#edit_journal_page
  .wrapper
    %h1 Editing Journal
    = render 'form'

app/views/journals/index.html.haml
%section#home_page
  .wrapper
    - if params[:year].blank?
      = render 'journals/index/choose_year'
    - elsif params[:month].blank?
      = render 'journals/index/choose_year_month'
    - elsif params[:day].blank?
      = render 'journals/index/choose_year_month_day'
    - elsif params[:year].present? && params[:month].present? && params[:day].present?
      = render 'journals/index/display_journals'

app/views/journals/index/_choose_year.html.haml
.time_title.clearfix
  %span
  %span
  %span
.directions
  %span Choose a Year
#choose_year_panel
  .row
    = link_to root_path(:year => "2016"), class: "year_box" do
      %h3 2016
= render 'journals/index/display_journals'

app/views/journals/index/_choose_year_month.html.haml
.time_title.clearfix
  %span#year=@year
  %span#month
  %span#day
.directions.hide.clearfix
  %span Choose a Month
#choose_month_panel
  .row.clearfix
    = link_to root_path(:year=>params[:year], :month=>"01"), class: "month_box_left" do
      %h3 January
    = link_to root_path(:year=>params[:year], :month=>"02"), class: "month_box_mid" do
      %h3 February
    = link_to root_path(:year=>params[:year], :month=>"03"), class: "month_box_right" do
      %h3 March
  .row.clearfix
    = link_to root_path(:year=>params[:year], :month=>"04"), class: "month_box_left" do
      %h3 April
    = link_to root_path(:year=>params[:year], :month=>"05"), class: "month_box_mid" do
      %h3 May
    = link_to root_path(:year=>params[:year], :month=>"06"), class: "month_box_right" do
      %h3 June
  .row.clearfix
    = link_to root_path(:year=>params[:year], :month=>"07"), class: "month_box_left" do
      %h3 July
    = link_to root_path(:year=>params[:year], :month=>"08"), class: "month_box_mid" do
      %h3 August
    = link_to root_path(:year=>params[:year], :month=>"09"), class: "month_box_right" do
      %h3 September
  .row.clearfix
    = link_to root_path(:year=>params[:year], :month=>"10"), class: "month_box_left" do
      %h3 October
    = link_to root_path(:year=>params[:year], :month=>"11"), class: "month_box_mid" do
      %h3 November
    = link_to root_path(:year=>params[:year], :month=>"12"), class: "month_box_right" do
      %h3 December

app/views/journals/index/_choose_year_month_day.html.haml
.time_title.clearfix
  %span#year=@year
  %span#month=@month_string
  %span#day
.directions.hide.full_width.clearfix
  %span Choose a Day
#choose_day_panel
  .weekday_label_bar
    %ul#weekdays_group.clearfix
      %li.weekday_label Sun
      %li.weekday_label Mon
      %li.weekday_label Tue
      %li.weekday_label Wed
      %li.weekday_label Thu
      %li.weekday_label Fri
      %li.weekday_label Sat
  .days_panel
    - @display_dates.each do |week|
      %ul.days_row.clearfix
        - week.each_with_index do |weekday, index|
          - if index.equal?(0)
            - if weekday.blank?
              %li.day_box.first_day_box
            - else
              = link_to root_path(:year=>params[:year], :month=>params[:month], :day=>weekday.to_s.rjust(2, '0')) do
                %li.day_box.first_day_box= weekday.to_s
          - elsif index.equal?(6)
            - if weekday.blank?
              %li.day_box.last_day_box
            - else
              = link_to root_path(:year=>params[:year], :month=>params[:month], :day=>weekday.to_s.rjust(2, '0')) do
                %li.day_box.last_day_box= weekday.to_s
          - else
            - if weekday.blank?
              %li.day_box
            - else
              = link_to root_path(:year=>params[:year], :month=>params[:month], :day=>weekday.to_s.rjust(2, '0')) do
                %li.day_box= weekday.to_s
= render 'journals/index/display_journals'

app/views/journals/index/_display_journals.html.haml
#journal_index_panel
  .wrapper
    .journal_listing
      %h1 Daily Journal(s)
      - @journals.each do |journal|
        = link_to journal do
          .journal_item.clearfix
            %h2= journal.date.strftime("%B %d, %Y")
            %span
              By
              = " ".concat(journal.user.email)

app/views/journals/new.html.haml
#new_journal_page
  .wrapper
    %h1 New Journal
    = render 'form'

app/views/journals/show.html.haml
%section#show_page
  .wrapper
    .time_title.clearfix
      %span#year= @year
      %span#month= @month
      %span#day= @day
    .content
      .content_top
        .content_section
          .content_header
            %h2 Improvements For Tomorrow
          .content_body
            = simple_format(@journal.improvement)

      .content_top
        .content_section
          .content_header
            %h2 Daily Metrics
          .content_body
            .row.clearfix
              %h3.content_sub_header Happiness Level (1-10)
              %span= @journal.happiness
            .row
              %h3.content_sub_header Did I meditate today?
              - if @journal.happiness
                %span= "Yes"
              - else
                %span= "No"
            .row
              %h3.content_sub_header Most Important Task Completed?
              - if @journal.task_complete
                %span= "Yes"
              - else
                %span= "No"
            .row
              %h3.content_sub_header Masburbation Count
              %span= @journal.masturbation
      .content_mid.clearfix
        .left
          .content_section
            .content_header
              %h2 Questions of the Day
            .content_body
              %h3 What is my wanted outcome?
              = simple_format(@journal.q1answers)
              %h3 Did I give it my all today?
              = simple_format(@journal.q2answers)
              %h3 Was today meaningful?
              = simple_format(@journal.q3answers)
              %h3 Was I doing what I love?
              = simple_format(@journal.q4answers)
        .right.right_show_fix
          .content_section
            .content_header
              %h2 Wins of the Day
            .content_body
              %h4 My wins today are that...
              %ul.content_list_group
                - @journal.wins.each do |win|
                  %li.content_list_item= win.win
          .content_section
            .content_header
              %h2 Lessons of the Day
            .content_body
              %h4 I learned that...
              %ul.content_list_group
                - @journal.lessons.each do |lesson|
                  %li.content_list_item= lesson.lesson
      .content_bot
        .content_section
          .content_header
            %h2 Daily Journal
          .content_body= simple_format(@journal.content)
      .row.button_group
        = link_to "Edit", edit_journal_path, class: "btn"
        = link_to "Delete", journal_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css", :rel => "stylesheet"}/
    %title BestselfJournal
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "https://www.google.com/jsapi"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body
    %section#header
      .wrapper
        %header.clearfix
          .logo
            %p= link_to "Self Reflection", root_path
          %nav
            = link_to "Home", root_path
            - if user_signed_in?
              = link_to "New Reflection", new_journal_path
              = link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              = link_to "Sign In", new_user_session_path
    .container
      .wrapper
        - flash.each do |name, msg|
          = content_tag :div, msg, class: "alert"
      = yield
    %footer#footer.hide
      .wrapper
        %h4 IT'S YOUR BOI, YONGYI XU